name = "virtupay_package_wvcp"

version = "0.1.1"

authors = [

{name="Peethani, Udaya Ramu", email="udayaramu.peethani@wellsfargo.com"},

{name="Cheyyur, Sai Lokesh", email="sailokesh.cheyyur@wellsfargo.com"},

description = "Virtual Card Engine for Wellsone Commercial Customers"

readme "README.md"

requires-python = ">=3.10"

classifiers = [

"Programming Language: Python :: 3",

"License:: Wells Fargo Internal Only",

"Operating System:: OS Independent",

[project.urls]

Homepage "https://github.wellsfargo.com/u692495/wvcp_vcg"

Issues = "https://github.wellsfargo.com/u692495/wvcp_vcg"
