CREATE SCHEMA IF NOT EXISTS wf_vcg_db
AUTHORIZATION edm_pg_rw_ddl_grp;
GRANT USAGE ON SCHEMA wf_vcg_db TO edm_pg_ro_grp;
GRANT ALL ON SCHEMA wf_vcg_db TO edm_pg_rw_ddl_grp;
GRANT USAGE ON SCHENA wf_vcg_db TO edm_Pg_rw_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE "U692495" IN SCHEMA wf_vcg_db
GRANT SELECT ON TABLES TO edm_pg_ro_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE "U692495" IN SCHEMA wf_vcg_db
GRANT ALL ON TABLES TO edm_pg_rw_ddl_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE "U692495" IN SCHEMA wf_vcg_db
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLES TO edm_pg_rw_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE edm_pg_rw_dd1_grp IN SCHEMA wf_vcg_db
GRANT USAGE ON TYPES TO edm_pg_ro_grp:
ALTER DEFAULT PRIVILEGES FOR ROLE edm_pg_rw_ddl_grp IN SCHEMA wf_vcg_db
GRANT USAGE ON TYPES TO edm_pg_rw_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE edm_pg_rw_ddl_grp IN SCHEMA wf_vcg_db
GRANT SELECT ON TABLES TO edm_pg_ro_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE edm_pg_rw_ddl_grp IN SCHEMA wf_vcg_db
GRANT ALL ON TABLES TO edm_pg_rw_ddl_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE edm_pg_rw_ddl_grp IN SCHEMA wf_VCg_db
GRANT INSERT, DELETE, SELECT, UPDATE ON TABLES TO edm_pg_rw_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE "U692495"


GRANT SELECT ON SEQUENCES TO edm_pg_ro_grp;


IN SCHEMA wf_vcg_db
GRANT SELECT ON SEQUENCES TO edm_pg_ro_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE "U692495" IN SCHEMA wf_vcg_db
GRANT ALL ON SEQUENCES TO edm_pg_rw_ddl_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE "U692495" IN SCHEMA wf_vcg_db
GRANT SELECT, UPDATE ON SEQUENCES TO edm_pg_rw_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE edm_pg_rw_ddl_grp IN SCHEMA wf_vcg_db
GRANT ALL ON SEQUENCES TO edm_pg_rw_ddl_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE edm_pg_rw_dd1_grp IN" SCHEMA wf_vcg_db
GRANT SELECT, UPDATE ON SEQUENCES TO edm_pg_rw_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE "U692495" IN SCHEMA wf_vcg_db
GRANT EXECUTE ON FUNCTIONS TO edm_pg_ro_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE "U692495" IN SCHEMA wf_vcg_db
GRANT EXECUTE ON FUNCTIONS TO edm_pg_rw_ddl_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE "U692495" IN SCHEMA wf_VCg_db
GRANT EXECUTE ON FUNCTIONS TO edm_pgirw_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE edm_pg_rw_ddl_grp IN SCHEMA wf_VCg_db
GRANT SELECT ON SEQUENCES TO edm_pg_ro_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE edm_pg_rw_ddl_grp IN SCHEMA wf_Vcg_db
GRANT EXECUTE ON FUNCTIONS TO edm_pg_ro_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE edm_pg_rw_ddl_grp IN SCHEMA wf_ycg_db
GRANT EXECUTE ON FUNCTIONS TO edm_pg_rw ddl_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE edm_pg_rw_ddl_grp IN SCHEMA wf_VCg_db
GRANT EXECUTE ON FUNCTIONS TO edm_pg_rw_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE "U692495" IN SCHEMA wf_vcg_db
GRANT USAGE ON TYPES TO edm. pg_ro_grp;
ALTER DEFAULT PRIVILEGES FOR ROLE "U692495" IN SCHEMA WF_VCg_db
GRANT USAGE ON TYPES TO edm_pg_rw_grp;
